import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Folder,FolderPlus,Files,Inbox,Trash2,MoreHorizontal,Pencil,FolderInput,RotateCcw,Search,RefreshCw,X,Check,ArrowRight} from 'lucide-react';

export const recordName=r=>r.displayName||`${r.problem.id?r.problem.id+'. ':''}${r.problem.title}`;

function EditDialog({config,folders,busy,onSubmit,onClose}){
 const ref=useRef(null),[name,setName]=useState(config.name||''),[folder,setFolder]=useState(config.folderId||''),[error,setError]=useState('');
 useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);
 const titles={createFolder:'新建专题',renameFolder:'重命名专题',deleteFolder:'删除专题',move:'移动到专题',rename:'重命名记录',trash:'放入回收站'};
 const needsName=['createFolder','renameFolder','rename'].includes(config.action);
 async function submit(e){e.preventDefault();setError('');try{await onSubmit({...config,...(needsName?{name}:{}),...(config.action==='move'?(folder==='__new'?{newFolderName:name}:{folderId:folder||null}):{})});onClose();}catch(e){setError(e.message);}}
 return createPortal(<dialog ref={ref} className="library-dialog" aria-labelledby="library-dialog-title" onCancel={e=>{if(busy)e.preventDefault();}} onClose={onClose}><form onSubmit={submit}><header><h2 id="library-dialog-title">{titles[config.action]}</h2><button type="button" className="icon-button" aria-label="关闭管理弹窗" disabled={busy} onClick={onClose}><X size={20}/></button></header>
  {config.action==='deleteFolder'?<p>删除「{config.name}」后，其中的记录会回到未分类，题解与交流内容都会保留。</p>:config.action==='trash'?<p>将 {config.ids.length} 条记录放入回收站？以后可以恢复，已导出的 Markdown 文件不会受影响。</p>:config.action==='move'?<><p>整理 {config.ids.length} 条记录，题解和追问保持完整。</p><label>目标专题<select aria-label="目标专题" autoFocus value={folder} onChange={e=>setFolder(e.target.value)}><option value="">未分类</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}<option value="__new">＋ 新建专题并移入</option></select></label>{folder==='__new'&&<label>新专题名称<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} required placeholder="例如：动态规划"/></label>}</>:<label>{config.action==='rename'?'记录显示名称':'专题名称'}<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={100} required placeholder="输入名称"/></label>}
  {config.action==='rename'&&<p className="library-help">只修改列表中的显示名称，原始题目和题解不变。</p>}{error&&<p className="error" role="alert">{error}</p>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button className={'primary '+(['trash','deleteFolder'].includes(config.action)?'danger-button':'')} disabled={busy||(needsName&&!name.trim())||(config.action==='move'&&folder==='__new'&&!name.trim())}>{busy?'保存中…':config.action==='trash'?'放入回收站':config.action==='deleteFolder'?'删除专题':'确认'}</button></footer>
 </form></dialog>,document.body);
}

export function LibraryManager({library,scope,onScopeChange,busy,onMutate,onRefresh,onOpen}){
 const [query,setQuery]=useState(''),[language,setLanguage]=useState('all'),[sort,setSort]=useState('updated'),[selected,setSelected]=useState([]),[dialog,setDialog]=useState(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const allCheck=useRef(null),folders=library.folders,records=library.records,trash=scope==='trash',disabled=busy||pending;
 const active=records.filter(r=>!r.deletedAt),discarded=records.filter(r=>r.deletedAt);
 const currentFolder=folders.find(f=>f.id===scope),title=scope==='all'?'全部记录':scope==='unfiled'?'未分类':trash?'回收站':currentFolder?.name||'全部记录';
 const scoped=(trash?discarded:active).filter(r=>['all','trash'].includes(scope)?true:scope==='unfiled'?!r.folderId:r.folderId===scope);
 const visible=scoped.filter(r=>(language==='all'||r.language===language)&&`${recordName(r)} ${r.problem.title} ${r.problem.id} ${r.language}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>{const key=sort==='created'?'createdAt':sort==='deleted'?'deletedAt':'updatedAt';return (b[key]||b.createdAt).localeCompare(a[key]||a.createdAt)||a.id.localeCompare(b.id);});
 useEffect(()=>{setSelected([]);},[scope,query,language]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{if(!trash&&sort==='deleted')setSort('updated');},[trash,sort]);
 useEffect(()=>{setSelected(s=>s.filter(id=>visible.some(r=>r.id===id)));},[library]);
 useEffect(()=>{if(allCheck.current)allCheck.current.indeterminate=selected.length>0&&selected.length<visible.length;},[selected.length,visible.length]);
 useEffect(()=>{if(!['all','unfiled','trash'].includes(scope)&&!currentFolder)onScopeChange('all');},[scope,currentFolder]);
 function selectOne(id){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 async function mutate(input){setPending(true);setError('');setNotice('');try{const result=await onMutate(input);setSelected([]);setNotice({createFolder:'专题已创建',renameFolder:'专题名称已更新',deleteFolder:'专题已删除，记录已移回未分类',move:'记录已移动',rename:'显示名称已更新',trash:'已放入回收站，可随时恢复',restore:'记录已恢复'}[input.action]);if(input.action==='createFolder')onScopeChange(result.createdFolder.id);return result;}catch(e){setError(e.message);throw e;}finally{setPending(false);}}
 async function refresh(){setPending(true);setError('');try{await onRefresh();setSelected([]);}catch(e){setError(e.message);}finally{setPending(false);}}
 const count=id=>active.filter(r=>r.folderId===id).length;
 function folderButton(id,label,Icon,total){return <button className={scope===id?'selected':''} onClick={()=>onScopeChange(id)} aria-current={scope===id?'page':undefined}><Icon size={18}/><span>{label}</span><small>{total}</small></button>;}
 return <section className="library-layout" aria-label="研习记录管理"><aside className="library-folders"><div className="library-folders-heading"><strong>我的专题</strong><button className="icon-button" title="新建专题" aria-label="新建专题" disabled={disabled} onClick={()=>setDialog({action:'createFolder'})}><FolderPlus size={19}/></button></div><nav aria-label="专题目录">{folderButton('all','全部记录',Files,active.length)}{folderButton('unfiled','未分类',Inbox,count(null))}<div className="folder-divider"/>{folders.map(f=><React.Fragment key={f.id}>{folderButton(f.id,f.name,Folder,count(f.id))}</React.Fragment>)}{!folders.length&&<p className="library-help">为知识建一个专题，<br/>从整理第一条记录开始。</p>}<div className="folder-divider"/>{folderButton('trash','回收站',Trash2,discarded.length)}</nav></aside>
 <div className="library-main"><header className="library-heading"><div><h2>{title}<span>{scoped.length}</span></h2><p>{trash?'删除的记录保留在这里，恢复时优先回到原专题。':'把相近的题目放在一起，让每次复习都有方向。'}</p></div><div className="library-heading-actions">{currentFolder&&<><button className="icon-button" title="重命名专题" aria-label="重命名专题" disabled={disabled} onClick={()=>setDialog({action:'renameFolder',folderId:scope,name:title})}><Pencil size={17}/></button><button className="icon-button" title="删除专题" aria-label="删除专题" disabled={disabled} onClick={()=>setDialog({action:'deleteFolder',folderId:scope,name:title})}><Trash2 size={17}/></button></>}<button className="icon-button" title="刷新列表" aria-label="刷新列表" disabled={pending} onClick={refresh}><RefreshCw size={17}/></button></div></header>
 <div className="library-filters"><label className="search-box"><Search size={17}/><input aria-label="搜索研习记录" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、题号、题名…"/>{query&&<button type="button" className="icon-button" aria-label="清除搜索" onClick={()=>setQuery('')}><X size={14}/></button>}</label><select aria-label="筛选记录语言" value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">全部语言</option>{['Java','C++','Python'].map(l=><option key={l}>{l}</option>)}</select><select aria-label="记录排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近更新</option><option value="created">最新创建</option>{trash&&<option value="deleted">最近删除</option>}</select></div>
 {busy&&<p className="library-status">Agent 正在生成，完成后即可整理记录。</p>}{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="library-notice" role="status"><Check size={16}/><span>{notice}</span><button type="button" className="icon-button" aria-label="关闭操作提示" title="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="library-bulk"><label><input ref={allCheck} type="checkbox" aria-label="全选当前结果" disabled={disabled||!visible.length} checked={visible.length>0&&selected.length===visible.length} onChange={e=>setSelected(e.target.checked?visible.map(r=>r.id):[])}/> {selected.length?`已选 ${selected.length} 条`:`当前 ${visible.length} 条`}</label><div>{selected.length>0&&(trash?<button className="secondary" disabled={disabled} onClick={()=>mutate({action:'restore',ids:selected}).catch(()=>{})}><RotateCcw size={15}/> 批量恢复</button>:<><button className="secondary" disabled={disabled} onClick={()=>setDialog({action:'move',ids:selected,folderId:currentFolder?.id})}><FolderInput size={15}/> 批量移动</button><button className="text-button library-danger" disabled={disabled} onClick={()=>setDialog({action:'trash',ids:selected})}><Trash2 size={15}/> 放入回收站</button></>)}</div></div>
 <div className="library-records">{visible.map(r=><div key={r.id} className={'library-record '+(selected.includes(r.id)?'checked':'')}><input type="checkbox" aria-label={'选择记录 '+recordName(r)} disabled={disabled} checked={selected.includes(r.id)} onChange={()=>selectOne(r.id)}/><button className="library-record-body" disabled={busy||trash} onClick={()=>onOpen(r)}><span className="library-record-icon"><Files size={20}/></span><div><strong>{recordName(r)}</strong>{r.displayName&&<span className="original-title">原题：{r.problem.id}. {r.problem.title}</span>}<small>{trash?'删除于 ':'更新于 '}{new Date(trash?r.deletedAt:r.updatedAt||r.createdAt).toLocaleString('zh-CN')} · {r.language} · {r.mode==='hint'?'渐进提示':'完整题解'}</small><span className="record-folder-label"><Folder size={12}/>{folders.find(f=>f.id===r.folderId)?.name||'未分类'}{r.savedPath&&<span> · 已导出</span>}</span></div></button>{trash?<button className="secondary" disabled={disabled} onClick={()=>mutate({action:'restore',ids:[r.id]}).catch(()=>{})}><RotateCcw size={15}/> 恢复</button>:<details className="record-menu" name="record-actions"><summary aria-label={'管理记录 '+recordName(r)}><MoreHorizontal size={20}/></summary><div>{[['move','移动到专题',FolderInput],['rename','重命名',Pencil],['trash','放入回收站',Trash2]].map(([action,label,Icon])=><button key={action} disabled={disabled} onClick={e=>{e.currentTarget.closest('details').open=false;setDialog({action,ids:[r.id],name:recordName(r),folderId:r.folderId});}}><Icon size={15}/>{label}</button>)}</div></details>}</div>)}</div>
 {!visible.length&&<div className="library-empty"><Folder size={40}/><h3>{query||language!=='all'?'没有匹配的记录':trash?'回收站是空的':currentFolder?'这个专题还没有记录':'这里还没有记录'}</h3><p>{query||language!=='all'?'试试其他关键词，或清除筛选条件。':trash?'放入回收站的记录可以在这里恢复。':currentFolder?'在全部记录中勾选题解，选择“批量移动”即可归档。':'生成题解后，会自动出现在未分类中。'}</p>{(query||language!=='all')?<button className="secondary" onClick={()=>{setQuery('');setLanguage('all');}}>清除筛选</button>:currentFolder?<button className="secondary" onClick={()=>onScopeChange('all')}>前往全部记录 <ArrowRight size={15}/></button>:null}</div>}
 </div>{dialog&&<EditDialog config={dialog} folders={folders} busy={pending} onSubmit={mutate} onClose={()=>setDialog(null)}/>}</section>;
}

export function RecordFolder({record,folders,disabled,onMove,onManage}){
 const [pending,setPending]=useState(false),[error,setError]=useState('');
 return <div className="work-record-folder"><Folder size={15}/><label>所属专题 <select aria-label="当前记录所属专题" disabled={disabled||pending} value={record.folderId||''} onChange={async e=>{const folderId=e.target.value||null;setPending(true);setError('');try{await onMove({action:'move',ids:[record.id],folderId});}catch(e){setError(e.message);}finally{setPending(false);}}}><option value="">未分类</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button className="text-button" onClick={onManage}>管理专题</button>{error&&<span role="alert">{error}</span>}</div>;
}
