import React,{useState,useEffect,useRef} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {X,Send,MessageCircle,BookOpen,Check} from 'lucide-react';
import {api} from './api.js';

export function StudyTools({record,busy,job,onRun,onCancel}){
 const [chat,setChat]=useState(false),[regen,setRegen]=useState(false),[text,setText]=useState(''),[feedback,setFeedback]=useState(''),[sessionMode,setSessionMode]=useState('reuse'),[pending,setPending]=useState(false),[error,setError]=useState('');
 const end=useRef(null);
 const drag=useRef(null),[position,setPosition]=useState(null);
 useEffect(()=>{const reset=()=>setPosition(null);window.addEventListener('resize',reset);return()=>window.removeEventListener('resize',reset);},[]);
 function beginDrag(e){if(e.target.closest('button'))return;const r=e.currentTarget.parentElement.getBoundingClientRect();drag.current={x:e.clientX-r.left,y:e.clientY-r.top,w:r.width,h:r.height};e.currentTarget.setPointerCapture(e.pointerId);}
 function moveDrag(e){const d=drag.current;if(!d)return;setPosition({left:Math.max(0,Math.min(window.innerWidth-d.w,e.clientX-d.x)),top:Math.max(0,Math.min(window.innerHeight-d.h,e.clientY-d.y)),right:'auto',bottom:'auto'});}
 useEffect(()=>{setChat(false);setRegen(false);setText('');setError('');},[record?.id]);
 useEffect(()=>{if(job?.action==='chat'&&busy)setChat(true);},[job?.id,record?.id]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[record?.messages?.length,chat,busy]);
 async function run(action){setPending(true);setError('');try{await onRun({action,recordId:record.id,sessionMode:action==='chat'?'reuse':sessionMode,feedback:action==='chat'?text:feedback});if(action==='chat')setText('');else{setRegen(false);setFeedback('');}}catch(e){setError(e.message);}finally{setPending(false);}}
 if(!record)return null;
 return <><div className="study-actions"><button className="secondary" onClick={()=>setChat(!chat)}><MessageCircle size={16}/> 继续追问 {record.messages?.length?`· ${record.messages.length/2}`:''}</button><button className="secondary" disabled={busy||pending} onClick={()=>setRegen(true)}>重新生成</button><small>第 {record.revision||1} 版 · 同一研习记录</small></div>
 {regen&&<div className="modal-backdrop"><dialog open className="modal" aria-modal="true" aria-label="重新生成" onKeyDown={e=>{if(e.key==='Escape')setRegen(false);}}><div className="modal-header"><h2>再打磨一次答案</h2><button autoFocus aria-label="关闭重新生成" className="icon-button" onClick={()=>setRegen(false)}><X/></button></div><p className="modal-intro">完成后更新当前研习记录；失败或取消会保留原答案。</p><label>生成方式<select value={sessionMode} onChange={e=>setSessionMode(e.target.value)}><option value="reuse">延续之前的会话</option><option value="new">在新会话中重新生成</option></select></label><label>希望如何改进（可选）<textarea className="manual-input" maxLength={15000} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="例如：请把双指针的移动过程解释得更细，并增加边界示例。"/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="modal-footer"><button className="secondary" onClick={()=>setRegen(false)}>取消</button><button className="primary" disabled={busy||pending} onClick={()=>run('regenerate')}>开始重新生成</button></div></dialog></div>}
 {chat&&<section className="chat-window" role="dialog" aria-label="继续追问" style={position}><header title="拖动标题栏可移动窗口" onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><div><MessageCircle size={18}/><strong>一起弄懂这道题</strong><small>{record.problem.title} · {record.agent==='harness'?'DeepSeek':'Codex'}</small></div><button className="icon-button" aria-label="收起追问" onClick={()=>setChat(false)}><X/></button></header><div className="chat-messages"><p className="chat-context">已关联当前题解与之前的交流，可直接提问。</p>{(record.messages||[]).map((m,i)=><div key={i} className={'chat-message '+m.role}><small>{m.role==='user'?'我':'Agent'}</small><article className="markdown"><Markdown remarkPlugins={[remarkGfm]}>{m.content}</Markdown></article></div>)}{busy&&job?.action==='chat'&&<p className="chat-context" role="status">{job.stage}… <button className="text-button" type="button" onClick={onCancel}>停止生成</button></p>}{(error||job?.status==='error')&&<p className="error" role="alert">{error||job.error}</p>}<div ref={end}/></div><form onSubmit={e=>{e.preventDefault();run('chat');}}><textarea aria-label="追问内容" value={text} maxLength={15000} onChange={e=>setText(e.target.value)} placeholder="哪里还没弄懂？输入你的问题…" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&text.trim()&&!busy&&!pending){e.preventDefault();run('chat');}}}/><div><small>Ctrl + Enter 发送 · 自动保存交流</small><button className="primary" disabled={busy||pending||!text.trim()}><Send size={15}/> 发送</button></div></form></section>}</>;
}

export function SkillEditor({onSaved}){
 const [original,setOriginal]=useState(null),[content,setContent]=useState(''),[preview,setPreview]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 useEffect(()=>{api('skill').then(r=>{
   let draft;try{draft=JSON.parse(sessionStorage.getItem('cc4-skill-draft'));}catch{}
   setOriginal(draft?.original??r.content);setContent(draft?.content??r.content);
   if(draft)setStatus('已恢复未保存草稿。'+(draft.original!==r.content?'文件已在其他位置修改，请复制保留草稿后重新载入最新文件。':''));
 }).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(original===null)return;try{if(content===original)sessionStorage.removeItem('cc4-skill-draft');else sessionStorage.setItem('cc4-skill-draft',JSON.stringify({content,original}));}catch{}},[content,original]);
 useEffect(()=>{const warn=e=>{e.preventDefault();e.returnValue='';};if(original!==null&&content!==original)window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[content,original]);
 async function reloadSaved(){try{const r=await api('skill');setOriginal(r.content);setContent(r.content);setError('');setStatus('已重新载入保存的版本。');}catch(e){setError(e.message);}}
 async function save(){setSaving(true);setError('');try{const r=await api('skill',{content,original},'PUT');setOriginal(r.content);setStatus('已保存，下次生成和追问立即生效。旧版本已备份。');onSaved(r.content);}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <><p className="modal-intro">直接调整教学风格、代码规范与讲解步骤。保存前可预览，保存时自动备份原文件。</p><div className="answer-tabs"><button className="secondary" onClick={()=>setPreview(!preview)}><BookOpen size={15}/> {preview?'返回编辑':'预览效果'}</button><small>{content.length} / 100000 字 {original!==null&&content!==original?'· 尚未保存':''}</small></div>{error&&<p className="error" role="alert">{error}</p>}{preview?<article className="markdown skill-content"><Markdown remarkPlugins={[remarkGfm]}>{content.replace(/^---[\s\S]*?---\s*/,'')}</Markdown></article>:<textarea className="skill-editor" aria-label="教学 Skill 源文" spellCheck={false} disabled={original===null} maxLength={100000} value={content} onChange={e=>{setContent(e.target.value);setStatus('');}}/>}{status&&<p role="status">{status}</p>}<div className="modal-footer"><button className="secondary" disabled={saving} onClick={reloadSaved}>舍弃草稿并重新载入</button><button className="primary" disabled={saving||original===null||content===original||!content.trim()} onClick={save}><Check size={16}/> {saving?'保存中…':'保存 Skill'}</button></div></>;
}
